// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATBgVqZ2jchVwX_eWkGfSZI_GaqIxQ7gE',
    appId: '1:429023634102:web:97e09445fb72f35fd2bc17',
    messagingSenderId: '429023634102',
    projectId: 'tomanena-c97cd',
    authDomain: 'tomanena-c97cd.firebaseapp.com',
    storageBucket: 'tomanena-c97cd.firebasestorage.app',
    measurementId: 'G-MYXDQHNRV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0BOLFN8djmCBkVnhUx5lgBWsLe_Nj9Yc',
    appId: '1:48589627982:android:7859376d7a8e155fd2191f',
    messagingSenderId: '48589627982',
    projectId: 'tamanina-90d04',
    storageBucket: 'tamanina-90d04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL6U_m3eX_j3gMQQ97lB55gxwi8PSbm6c',
    appId: '1:48589627982:ios:8fe5b5aa5be46cd9d2191f',
    messagingSenderId: '48589627982',
    projectId: 'tamanina-90d04',
    storageBucket: 'tamanina-90d04.firebasestorage.app',
    iosBundleId: 'com.example.tamanina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYsphgl3EQJpsNSn-j8f0PdAsbFWkju9Y',
    appId: '1:429023634102:ios:11f8b449b37d5f33d2bc17',
    messagingSenderId: '429023634102',
    projectId: 'tomanena-c97cd',
    storageBucket: 'tomanena-c97cd.firebasestorage.app',
    iosBundleId: 'com.example.tamanina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATBgVqZ2jchVwX_eWkGfSZI_GaqIxQ7gE',
    appId: '1:429023634102:web:87dcf34d4f1ccf8fd2bc17',
    messagingSenderId: '429023634102',
    projectId: 'tomanena-c97cd',
    authDomain: 'tomanena-c97cd.firebaseapp.com',
    storageBucket: 'tomanena-c97cd.firebasestorage.app',
    measurementId: 'G-ZK22S67WBL',
  );
}